[tool.poetry]
name = "innohassle-parsers"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "schedule/README.md"

[tool.poetry.dependencies]
python = "^3.10"
google-api-python-client = "^2.73.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^1.0.0"
pandas = "^2.0.3"
pydantic = "~1.10"
icalendar = "^5.0.4"
google = {extras = ["auth"], version = "^3.0.0"}

[tool.poetry.group.dev.dependencies]
sphinx-rtd-theme = "^1.2.2"
sphinx = "6"
autodoc-pydantic = "^1.8.0"
black = "^23.3.0"

